import type {
  ExperienceCoordination,
  ExperienceItem,
  ExperiencePromotion,
  ExperienceReservation,
  ExperienceReview,
} from "./types";

export const EXPERIENCES: ExperienceItem[] = [
  {
    id: "exp-1",
    name: "Sunrise Rice Terrace Trek",
    description: "Guided sunrise trek with local storytellers and breakfast at the village hall.",
    shortDescription: "A low-intensity sunrise trek with local breakfast.",
    category: "nature",
    locationName: "Sari Alam Terrace Route",
    locationAddress: "Sari Alam Village, Wonosobo",
    latitude: -7.358,
    longitude: 109.901,
    targetVillage: "Sari Alam",
    scheduleStart: "2026-05-14T05:30:00+07:00",
    scheduleEnd: "2026-05-14T09:30:00+07:00",
    isMultiDay: false,
    recurringPattern: "weekly",
    totalCapacity: 80,
    ticketTypes: [
      {
        id: "tkt-1",
        name: "Regular",
        description: "Entry + local breakfast",
        price: 95000,
        quota: 60,
        sold: 42,
        perPersonPrice: true,
        includes: ["Guide", "Breakfast"],
      },
      {
        id: "tkt-2",
        name: "Group (5 pax)",
        description: "Discounted package for groups",
        price: 400000,
        quota: 20,
        sold: 8,
        perPersonPrice: false,
        groupSize: 5,
        includes: ["Guide", "Breakfast", "Photos"],
      },
    ],
    media: ["terrace-1.jpg", "terrace-2.jpg"],
    posterImage: "terrace-poster.jpg",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    contactPerson: "Raka Nur",
    contactPhone: "0812000111",
    contactEmail: "raka@experience.id",
    cancellationPolicy: "Full refund up to 48 hours before event.",
    whatToBring: "Comfortable shoes and drinking water.",
    minAge: 10,
    difficultyLevel: "easy",
    languages: ["id", "en"],
    insuranceIncluded: true,
    itinerary: [
      { time: "05:30", activity: "Gathering point", location: "Village Hall", isOptional: false },
      { time: "06:00", endTime: "07:30", activity: "Sunrise trekking", location: "Terrace Route", isOptional: false },
      { time: "08:00", activity: "Breakfast & sharing", location: "Village Hall", isOptional: false },
    ],
    facilitiesNeeded: ["Village Hall"],
    status: "ticket_sales_open",
    averageRating: 4.6,
    totalReviews: 34,
    totalBookings: 50,
    monthlyRevenue: 7850000,
  },
  {
    id: "exp-2",
    name: "Village Culture Night",
    description: "Evening cultural performance and culinary mini festival.",
    shortDescription: "Culture showcase with local culinary stations.",
    category: "festival",
    locationName: "Village Hall",
    locationAddress: "Sari Alam Village Center",
    latitude: -7.359,
    longitude: 109.904,
    targetVillage: "Sari Alam",
    scheduleStart: "2026-05-20T18:00:00+07:00",
    scheduleEnd: "2026-05-20T22:00:00+07:00",
    isMultiDay: false,
    totalCapacity: 160,
    ticketTypes: [
      {
        id: "tkt-3",
        name: "Regular",
        description: "General entry",
        price: 120000,
        quota: 120,
        sold: 36,
        perPersonPrice: true,
        includes: ["Entry", "Welcome drink"],
      },
    ],
    media: ["culture-1.jpg"],
    posterImage: "culture-poster.jpg",
    contactPerson: "Nina Putri",
    contactPhone: "0812000222",
    contactEmail: "nina@experience.id",
    cancellationPolicy: "Non-refundable within 24 hours.",
    itinerary: [
      { time: "18:00", activity: "Opening dance", isOptional: false },
      { time: "19:00", activity: "Culinary expo", isOptional: false },
      { time: "20:30", activity: "Music performance", isOptional: false },
    ],
    status: "under_review",
    averageRating: 4.3,
    totalReviews: 12,
    totalBookings: 36,
    monthlyRevenue: 4320000,
  },
];

export const EXPERIENCE_RESERVATIONS: ExperienceReservation[] = [
  {
    id: "res-1",
    experienceId: "exp-1",
    experienceName: "Sunrise Rice Terrace Trek",
    customerName: "Dewi Lestari",
    customerEmail: "dewi@example.com",
    customerPhone: "0812111222",
    ticketTypeId: "tkt-1",
    ticketTypeName: "Regular",
    quantity: 2,
    totalPrice: 190000,
    paymentStatus: "success",
    bookingStatus: "confirmed",
    isWaitlist: false,
    createdAt: "2026-04-11",
  },
  {
    id: "res-2",
    experienceId: "exp-1",
    experienceName: "Sunrise Rice Terrace Trek",
    customerName: "Tomo Nakamura",
    customerEmail: "tomo@example.com",
    customerPhone: "0812333444",
    ticketTypeId: "tkt-2",
    ticketTypeName: "Group (5 pax)",
    quantity: 1,
    totalPrice: 400000,
    paymentStatus: "pending",
    bookingStatus: "confirmed",
    isWaitlist: true,
    groupSize: 5,
    createdAt: "2026-04-10",
  },
];

export const EXPERIENCE_COORDINATIONS: ExperienceCoordination[] = [
  {
    id: "coord-1",
    experienceId: "exp-2",
    targetVillage: "Sari Alam",
    status: "under_review",
    messages: [
      {
        id: "msg-1",
        senderRole: "organizer",
        senderName: "Nina Putri",
        content: "We propose using the village hall and parking lot for culture night.",
        createdAt: "2026-04-09T10:00:00+07:00",
      },
      {
        id: "msg-2",
        senderRole: "village_admin",
        senderName: "Village Admin",
        content: "Please provide final participant estimate and cleanup plan.",
        createdAt: "2026-04-09T14:00:00+07:00",
      },
    ],
    facilityRequests: [
      { facilityId: "fac-1", facilityName: "Village Hall", date: "2026-05-20", hours: 6, rentalPrice: 1500000 },
    ],
    revenueSplit: { organizer: 60, village: 25, platform: 15 },
    paymentSchedule: [
      { milestone: "dp", percent: 30, amount: 1296000, dueDate: "2026-04-20", paid: false },
      { milestone: "second", percent: 40, amount: 1728000, dueDate: "2026-05-13", paid: false },
      { milestone: "final", percent: 30, amount: 1296000, dueDate: "2026-05-20", paid: false },
    ],
    contractRef: "CTR-EXP-2026-019",
    createdAt: "2026-04-09",
    updatedAt: "2026-04-11",
  },
];

export const EXPERIENCE_PROMOTIONS: ExperiencePromotion[] = [
  {
    id: "pro-1",
    experienceId: "exp-1",
    name: "Early Bird Trek",
    type: "early_bird",
    discountType: "percentage",
    discountValue: 15,
    validFrom: "2026-04-10",
    validTo: "2026-05-01",
    status: "active",
  },
  {
    id: "pro-2",
    experienceId: "exp-2",
    name: "Culture Group Deal",
    type: "group_discount",
    discountType: "fixed",
    discountValue: 30000,
    validFrom: "2026-04-15",
    validTo: "2026-05-15",
    promoCode: "BUDAYA30",
    status: "inactive",
  },
];

export const EXPERIENCE_REVIEWS: ExperienceReview[] = [
  {
    id: "rev-1",
    experienceId: "exp-1",
    reviewerName: "Ari Santoso",
    rating: 5,
    comment: "Great guide and amazing sunrise view.",
    createdAt: "2026-04-08",
    organizerResponse: "Thank you for joining, see you again.",
  },
  {
    id: "rev-2",
    experienceId: "exp-1",
    reviewerName: "Mika Ito",
    rating: 4,
    comment: "Very enjoyable, but transport information can be clearer.",
    createdAt: "2026-04-06",
  },
];

export const VILLAGE_FACILITIES = [
  { id: "fac-1", name: "Village Hall", availability: "available", price: 1500000 },
  { id: "fac-2", name: "Parking Area", availability: "limited", price: 350000 },
  { id: "fac-3", name: "Open Stage", availability: "unavailable", price: 750000 },
] as const;
