import type {
  ExperienceCoordination,
  ExperienceItem,
  ExperiencePromotion,
  ExperienceReservation,
  ExperienceReview,
  Speaker,
  EventDocument,
  EventNotification,
  PostEventSurvey,
} from "./types";

export const SPEAKERS: Speaker[] = [
  {
    id: "spk-1",
    name: "Pak Wayan Sudarma",
    title: "Village Cultural Historian",
    bio: "30+ years preserving traditional stories and rituals of Sari Alam village.",
    photoUrl: "wayan-sudarma.jpg",
    topics: ["cultural heritage", "local history", "traditional rituals"],
    email: "wayan@sarialam.id",
    socialMedia: [{ platform: "instagram", url: "https://instagram.com/wayansudarma" }],
  },
  {
    id: "spk-2",
    name: "Ibu Ratna Dewi",
    title: "Head Chef & Culinary Expert",
    bio: "Award-winning local chef specializing in traditional Javanese cuisine.",
    photoUrl: "ratna-dewi.jpg",
    topics: ["culinary arts", "traditional recipes", "food culture"],
    email: "ratna@sarialam.id",
    phone: "0812555666",
  },
  {
    id: "spk-3",
    name: "Made Arjuna",
    title: "Nature Guide & Photographer",
    bio: "Certified mountain guide with expertise in flora and fauna photography.",
    topics: ["nature photography", "trekking", "biodiversity"],
    socialMedia: [
      { platform: "instagram", url: "https://instagram.com/madearjuna" },
      { platform: "youtube", url: "https://youtube.com/@madearjuna" },
    ],
  },
];

export const EXPERIENCES: ExperienceItem[] = [
  {
    id: "exp-1",
    name: "Sunrise Rice Terrace Trek",
    description: "Guided sunrise trek with local storytellers and breakfast at the village hall.",
    shortDescription: "A low-intensity sunrise trek with local breakfast.",
    category: "nature",
    visibility: "public",
    locationType: "offline",
    locationName: "Sari Alam Terrace Route",
    locationAddress: "Sari Alam Village, Wonosobo",
    latitude: -7.358,
    longitude: 109.901,
    targetVillage: "Sari Alam",
    scheduleStart: "2026-05-14T05:30:00+07:00",
    scheduleEnd: "2026-05-14T09:30:00+07:00",
    isMultiDay: false,
    recurringPattern: "weekly",
    totalCapacity: 80,
    ticketTypes: [
      {
        id: "tkt-1",
        name: "Regular",
        description: "Entry + local breakfast",
        price: 95000,
        quota: 60,
        sold: 42,
        perPersonPrice: true,
        includes: ["Guide", "Breakfast"],
        salesStart: "2026-04-01",
        salesEnd: "2026-05-13",
        refundPolicy: "full",
      },
      {
        id: "tkt-2",
        name: "Group (5 pax)",
        description: "Discounted package for groups",
        price: 400000,
        quota: 20,
        sold: 8,
        perPersonPrice: false,
        groupSize: 5,
        includes: ["Guide", "Breakfast", "Photos"],
        salesStart: "2026-04-01",
        salesEnd: "2026-05-13",
        refundPolicy: "partial",
      },
    ],
    speakers: [SPEAKERS[0], SPEAKERS[2]],
    media: ["terrace-1.jpg", "terrace-2.jpg"],
    posterImage: "terrace-poster.jpg",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    contactPerson: "Raka Nur",
    contactPhone: "0812000111",
    contactEmail: "raka@experience.id",
    cancellationPolicy: "Full refund up to 48 hours before event.",
    whatToBring: "Comfortable shoes and drinking water.",
    minAge: 10,
    difficultyLevel: "easy",
    languages: ["id", "en"],
    insuranceIncluded: true,
    itinerary: [
      { time: "05:30", activity: "Gathering point", location: "Village Hall", isOptional: false },
      { time: "06:00", endTime: "07:30", activity: "Sunrise trekking", location: "Terrace Route", isOptional: false, speakerId: "spk-3" },
      { time: "08:00", activity: "Breakfast & sharing", location: "Village Hall", isOptional: false, speakerId: "spk-1" },
    ],
    facilitiesNeeded: ["Village Hall"],
    documents: [
      { id: "doc-1", experienceId: "exp-1", name: "Event Permit 2026", type: "permit", url: "/docs/permit-exp1.pdf", fileSize: 245000, uploadedAt: "2026-03-15" },
      { id: "doc-2", experienceId: "exp-1", name: "Rundown - Sunrise Trek", type: "rundown", url: "/docs/rundown-exp1.pdf", fileSize: 128000, uploadedAt: "2026-04-01" },
    ],
    notifications: [
      { id: "notif-1", experienceId: "exp-1", type: "reminder", title: "Event Tomorrow!", message: "Don't forget to bring comfortable shoes.", scheduledAt: "2026-05-13T18:00:00+07:00", recipientCount: 50, status: "scheduled" },
    ],
    status: "ticket_sales_open",
    averageRating: 4.6,
    totalReviews: 34,
    totalBookings: 50,
    monthlyRevenue: 7850000,
    totalCheckedIn: 42,
    totalNoShow: 3,
  },
  {
    id: "exp-2",
    name: "Village Culture Night",
    description: "Evening cultural performance and culinary mini festival.",
    shortDescription: "Culture showcase with local culinary stations.",
    category: "festival",
    visibility: "public",
    locationType: "hybrid",
    onlineUrl: "https://stream.dewi.id/culture-night",
    locationName: "Village Hall",
    locationAddress: "Sari Alam Village Center",
    latitude: -7.359,
    longitude: 109.904,
    targetVillage: "Sari Alam",
    scheduleStart: "2026-05-20T18:00:00+07:00",
    scheduleEnd: "2026-05-20T22:00:00+07:00",
    isMultiDay: false,
    totalCapacity: 160,
    maxOnlineCapacity: 500,
    ticketTypes: [
      {
        id: "tkt-3",
        name: "Regular",
        description: "General entry",
        price: 120000,
        quota: 120,
        sold: 36,
        perPersonPrice: true,
        includes: ["Entry", "Welcome drink"],
        refundPolicy: "non_refundable",
      },
      {
        id: "tkt-4",
        name: "Online Stream",
        description: "Virtual attendance via livestream",
        price: 35000,
        quota: 500,
        sold: 87,
        perPersonPrice: true,
        includes: ["Livestream access", "Digital souvenir"],
        refundPolicy: "full",
      },
    ],
    speakers: [SPEAKERS[0], SPEAKERS[1]],
    media: ["culture-1.jpg"],
    posterImage: "culture-poster.jpg",
    contactPerson: "Nina Putri",
    contactPhone: "0812000222",
    contactEmail: "nina@experience.id",
    cancellationPolicy: "Non-refundable within 24 hours.",
    itinerary: [
      { time: "18:00", activity: "Opening dance", isOptional: false, speakerId: "spk-1" },
      { time: "19:00", activity: "Culinary expo", isOptional: false, speakerId: "spk-2" },
      { time: "20:30", activity: "Music performance", isOptional: false },
    ],
    facilitiesNeeded: ["Village Hall", "Parking Area"],
    documents: [
      { id: "doc-3", experienceId: "exp-2", name: "Village Hall Contract", type: "contract", url: "/docs/contract-exp2.pdf", fileSize: 340000, uploadedAt: "2026-04-05" },
      { id: "doc-4", experienceId: "exp-2", name: "Invoice - Facility Rental", type: "invoice", url: "/docs/invoice-exp2.pdf", fileSize: 89000, uploadedAt: "2026-04-10" },
    ],
    notifications: [
      { id: "notif-2", experienceId: "exp-2", type: "update", title: "New performer added!", message: "Local gamelan ensemble confirmed.", sentAt: "2026-04-15T10:00:00+07:00", recipientCount: 36, status: "sent" },
      { id: "notif-3", experienceId: "exp-2", type: "promotion", title: "Early Bird Ends Soon", message: "Last chance to grab 15% off!", scheduledAt: "2026-05-01T08:00:00+07:00", recipientCount: 200, status: "draft" },
    ],
    status: "under_review",
    averageRating: 4.3,
    totalReviews: 12,
    totalBookings: 36,
    monthlyRevenue: 4320000,
    totalCheckedIn: 30,
    totalNoShow: 2,
  },
];

export const EXPERIENCE_RESERVATIONS: ExperienceReservation[] = [
  {
    id: "res-1",
    experienceId: "exp-1",
    experienceName: "Sunrise Rice Terrace Trek",
    customerName: "Dewi Lestari",
    customerEmail: "dewi@example.com",
    customerPhone: "0812111222",
    ticketTypeId: "tkt-1",
    ticketTypeName: "Regular",
    quantity: 2,
    totalPrice: 190000,
    paymentStatus: "success",
    bookingStatus: "confirmed",
    isWaitlist: false,
    qrCode: "QR-RES1-EXP1-2026",
    eTicketUrl: "/tickets/e-ticket-res1.pdf",
    createdAt: "2026-04-11",
  },
  {
    id: "res-2",
    experienceId: "exp-1",
    experienceName: "Sunrise Rice Terrace Trek",
    customerName: "Tomo Nakamura",
    customerEmail: "tomo@example.com",
    customerPhone: "0812333444",
    ticketTypeId: "tkt-2",
    ticketTypeName: "Group (5 pax)",
    quantity: 1,
    totalPrice: 400000,
    paymentStatus: "pending",
    bookingStatus: "confirmed",
    isWaitlist: true,
    groupSize: 5,
    qrCode: "QR-RES2-EXP1-2026",
    createdAt: "2026-04-10",
  },
  {
    id: "res-3",
    experienceId: "exp-2",
    experienceName: "Village Culture Night",
    customerName: "Budi Santoso",
    customerEmail: "budi@example.com",
    customerPhone: "0812555666",
    ticketTypeId: "tkt-3",
    ticketTypeName: "Regular",
    quantity: 3,
    totalPrice: 360000,
    paymentStatus: "success",
    bookingStatus: "checked_in",
    isWaitlist: false,
    qrCode: "QR-RES3-EXP2-2026",
    checkInTime: "2026-05-20T17:45:00+07:00",
    createdAt: "2026-04-18",
  },
  {
    id: "res-4",
    experienceId: "exp-2",
    experienceName: "Village Culture Night",
    customerName: "Sarah Chen",
    customerEmail: "sarah@example.com",
    customerPhone: "0812777888",
    ticketTypeId: "tkt-4",
    ticketTypeName: "Online Stream",
    quantity: 1,
    totalPrice: 35000,
    paymentStatus: "success",
    bookingStatus: "confirmed",
    isWaitlist: false,
    qrCode: "QR-RES4-EXP2-2026",
    eTicketUrl: "/tickets/e-ticket-res4.pdf",
    createdAt: "2026-04-20",
  },
];

export const EXPERIENCE_COORDINATIONS: ExperienceCoordination[] = [
  {
    id: "coord-1",
    experienceId: "exp-2",
    targetVillage: "Sari Alam",
    status: "under_review",
    messages: [
      {
        id: "msg-1",
        senderRole: "organizer",
        senderName: "Nina Putri",
        content: "We propose using the village hall and parking lot for culture night.",
        createdAt: "2026-04-09T10:00:00+07:00",
      },
      {
        id: "msg-2",
        senderRole: "village_admin",
        senderName: "Village Admin",
        content: "Please provide final participant estimate and cleanup plan.",
        createdAt: "2026-04-09T14:00:00+07:00",
      },
    ],
    facilityRequests: [
      { facilityId: "fac-1", facilityName: "Village Hall", date: "2026-05-20", hours: 6, rentalPrice: 1500000 },
    ],
    revenueSplit: { organizer: 60, village: 25, platform: 15 },
    paymentSchedule: [
      { milestone: "dp", percent: 30, amount: 1296000, dueDate: "2026-04-20", paid: false },
      { milestone: "second", percent: 40, amount: 1728000, dueDate: "2026-05-13", paid: false },
      { milestone: "final", percent: 30, amount: 1296000, dueDate: "2026-05-20", paid: false },
    ],
    contractRef: "CTR-EXP-2026-019",
    createdAt: "2026-04-09",
    updatedAt: "2026-04-11",
  },
];

export const EXPERIENCE_PROMOTIONS: ExperiencePromotion[] = [
  {
    id: "pro-1",
    experienceId: "exp-1",
    name: "Early Bird Trek",
    type: "early_bird",
    discountType: "percentage",
    discountValue: 15,
    validFrom: "2026-04-10",
    validTo: "2026-05-01",
    status: "active",
  },
  {
    id: "pro-2",
    experienceId: "exp-2",
    name: "Culture Group Deal",
    type: "group_discount",
    discountType: "fixed",
    discountValue: 30000,
    validFrom: "2026-04-15",
    validTo: "2026-05-15",
    promoCode: "BUDAYA30",
    status: "inactive",
  },
];

export const EXPERIENCE_REVIEWS: ExperienceReview[] = [
  {
    id: "rev-1",
    experienceId: "exp-1",
    reviewerName: "Ari Santoso",
    rating: 5,
    comment: "Great guide and amazing sunrise view.",
    createdAt: "2026-04-08",
    organizerResponse: "Thank you for joining, see you again.",
  },
  {
    id: "rev-2",
    experienceId: "exp-1",
    reviewerName: "Mika Ito",
    rating: 4,
    comment: "Very enjoyable, but transport information can be clearer.",
    createdAt: "2026-04-06",
  },
];

export const VILLAGE_FACILITIES = [
  { id: "fac-1", name: "Village Hall", availability: "available", price: 1500000 },
  { id: "fac-2", name: "Parking Area", availability: "limited", price: 350000 },
  { id: "fac-3", name: "Open Stage", availability: "unavailable", price: 750000 },
] as const;

export const POST_EVENT_SURVEYS: PostEventSurvey[] = [
  {
    id: "survey-1",
    experienceId: "exp-1",
    title: "Sunrise Trek Feedback",
    questions: [
      { id: "q1", question: "How would you rate the overall experience?", type: "rating" },
      { id: "q2", question: "What did you enjoy most?", type: "text" },
      { id: "q3", question: "Would you recommend this to others?", type: "multiple_choice", options: ["Definitely", "Probably", "Not sure", "No"] },
      { id: "q4", question: "Rate the guide quality", type: "rating" },
    ],
    totalResponses: 28,
    averageSatisfaction: 4.5,
    createdAt: "2026-05-14",
  },
];
