import type {
  Accommodation,
  AccommodationSubmissionEvent,
  BankAccount,
  Payment,
  PaymentItem,
  PaymentSplit,
  Promotion,
  Reservation,
  Review,
  Room,
  WithdrawalRequest,
} from "@/types";

const accommodationA: Accommodation = {
  id: "acc-1",
  partnerId: "2",
  name: "Homestay Bukit Hijau",
  slug: "homestay-bukit-hijau",
  description:
    "Homestay dengan suasana pegunungan, dekat area trekking, dan fasilitas lengkap untuk keluarga maupun rombongan kecil.",
  shortDescription: "Penginapan nyaman dengan pemandangan sawah dan pegunungan.",
  address: "Jl. Bukit Hijau No. 5",
  village: "Sari Alam",
  district: "Mojotengah",
  regency: "Wonosobo",
  province: "Jawa Tengah",
  postalCode: "56351",
  latitude: -7.3641,
  longitude: 109.912,
  geoTagVerified: true,
  images: [
    {
      id: "img-1",
      accommodationId: "acc-1",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
      isPrimary: true,
      category: "exterior",
      width: 1920,
      height: 1280,
      sizeKb: 420,
      qualityScore: 88,
      order: 1,
    },
  ],
  facilities: [
    {
      id: "fac-1",
      accommodationId: "acc-1",
      category: "general",
      name: "WiFi",
      isAvailable: true,
    },
    {
      id: "fac-2",
      accommodationId: "acc-1",
      category: "service",
      name: "Breakfast",
      isAvailable: true,
      availabilityNote: "06:00 - 10:00",
    },
  ],
  documents: [
    {
      id: "doc-1",
      accommodationId: "acc-1",
      type: "business_license",
      name: "NIB-2026-0082",
      fileUrl: "https://example.com/docs/nib-2026-0082.pdf",
      fileSize: 1200,
      isVerified: true,
    },
    {
      id: "doc-2",
      accommodationId: "acc-1",
      type: "tourism_license",
      name: "TDUP-WNS-112",
      fileUrl: "https://example.com/docs/tdup-wns-112.pdf",
      fileSize: 980,
      isVerified: true,
    },
  ],
  priceRange: {
    min: 300000,
    max: 850000,
    currency: "IDR",
  },
  additionalFees: [
    {
      name: "Biaya Kebersihan",
      amount: 50000,
      type: "per_stay",
      isOptional: false,
    },
  ],
  submissionStatus: "approved",
  submittedAt: "2026-03-01",
  approvedAt: "2026-03-03",
  reviewedBy: "admin-1",
  isPublished: true,
  rating: 4.7,
  totalReviews: 124,
  createdAt: "2026-02-24",
  updatedAt: "2026-04-01",
};

const accommodationB: Accommodation = {
  ...accommodationA,
  id: "acc-2",
  name: "Villa Puncak Embun",
  slug: "villa-puncak-embun",
  shortDescription: "Villa modern untuk rombongan dan staycation premium.",
  latitude: -7.358,
  longitude: 109.905,
  submissionStatus: "submitted",
  submittedAt: "2026-04-06",
  approvedAt: undefined,
  isPublished: false,
  totalReviews: 0,
  rating: 0,
};

const accommodationC: Accommodation = {
  ...accommodationA,
  id: "acc-3",
  name: "Guest House Cendana",
  slug: "guest-house-cendana",
  shortDescription: "Guest house hemat untuk backpacker dan keluarga kecil.",
  submissionStatus: "revision",
  rejectionReason: "Foto interior minim pencahayaan dan dokumen sanitasi belum valid.",
  rejectionDetails: [
    "Upload minimal 3 foto interior dengan pencahayaan memadai.",
    "Sertifikat kesehatan sudah kedaluwarsa.",
  ],
  submittedAt: "2026-04-02",
  isPublished: false,
};

export const ACCOMMODATIONS: Accommodation[] = [
  accommodationA,
  accommodationB,
  accommodationC,
];

export const ACCOMMODATION_ROOMS: Room[] = [
  {
    id: "room-1",
    name: "Deluxe View Sawah",
    roomCode: "DLX-101",
    type: "Deluxe",
    description: "Kamar favorit dengan balkon kecil dan pemandangan sawah terbuka.",
    bedType: "1 King Bed",
    capacity: 2,
    pricePerNight: 450000,
    sizeSqm: 28,
    totalUnits: 4,
    availableUnits: 3,
    status: "available",
    floor: "Lantai 1",
    view: "Sawah",
    images: ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85"],
    amenities: ["AC", "WiFi", "Smart TV"],
    breakfastIncluded: true,
    smokingAllowed: false,
    lastCleanedAt: "2026-04-08T10:30:00Z",
    accommodationId: "acc-1",
  },
  {
    id: "room-2",
    name: "Family Suite",
    roomCode: "FAM-201",
    type: "Suite",
    description: "Suite luas untuk keluarga dengan area duduk terpisah.",
    bedType: "1 Queen Bed + 2 Single Bed",
    capacity: 4,
    pricePerNight: 850000,
    sizeSqm: 42,
    totalUnits: 2,
    availableUnits: 0,
    status: "booked",
    floor: "Lantai 2",
    view: "Gunung",
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267"],
    amenities: ["AC", "WiFi", "Bathtub", "Mini Bar"],
    breakfastIncluded: true,
    smokingAllowed: false,
    lastCleanedAt: "2026-04-07T14:00:00Z",
    accommodationId: "acc-1",
  },
  {
    id: "room-3",
    name: "Garden Twin",
    roomCode: "GDN-102",
    type: "Deluxe Twin",
    description: "Kamar twin nyaman dekat taman belakang dan area api unggun.",
    bedType: "2 Single Bed",
    capacity: 2,
    pricePerNight: 400000,
    sizeSqm: 24,
    totalUnits: 3,
    availableUnits: 1,
    status: "available",
    floor: "Lantai 1",
    view: "Taman",
    images: ["https://images.unsplash.com/photo-1505692952047-1a78307da8f2"],
    amenities: ["AC", "WiFi", "Work Desk", "Coffee Set"],
    breakfastIncluded: false,
    smokingAllowed: false,
    lastCleanedAt: "2026-04-08T08:15:00Z",
    accommodationId: "acc-1",
  },
  {
    id: "room-4",
    name: "Standard Room A",
    roomCode: "STD-001",
    type: "Standard",
    description: "Tipe ekonomis untuk tamu solo dan pasangan singkat menginap.",
    bedType: "1 Double Bed",
    capacity: 2,
    pricePerNight: 320000,
    sizeSqm: 18,
    totalUnits: 5,
    availableUnits: 0,
    status: "maintenance",
    floor: "Lantai 1",
    view: "Halaman Dalam",
    images: ["https://images.unsplash.com/photo-1484154218962-a197022b5858"],
    amenities: ["Fan", "WiFi"],
    breakfastIncluded: false,
    smokingAllowed: false,
    maintenanceNote: "Perbaikan AC portable dan pengecatan ulang dinding.",
    accommodationId: "acc-2",
  },
  {
    id: "room-5",
    name: "Sky Loft",
    roomCode: "SKY-301",
    type: "Loft",
    description: "Loft premium untuk rombongan kecil dengan jendela panorama.",
    bedType: "1 King Bed + Sofa Bed",
    capacity: 3,
    pricePerNight: 920000,
    sizeSqm: 46,
    totalUnits: 2,
    availableUnits: 1,
    status: "available",
    floor: "Lantai 3",
    view: "Lembah",
    images: ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85"],
    amenities: ["AC", "WiFi", "Smart TV", "Pantry", "Balcony"],
    breakfastIncluded: true,
    smokingAllowed: false,
    lastCleanedAt: "2026-04-08T12:00:00Z",
    accommodationId: "acc-2",
  },
  {
    id: "room-6",
    name: "Backpacker Pod",
    roomCode: "BKP-01",
    type: "Capsule",
    description: "Pilihan hemat untuk backpacker dengan locker pribadi dan area komunal.",
    bedType: "1 Capsule Bed",
    capacity: 1,
    pricePerNight: 180000,
    sizeSqm: 8,
    totalUnits: 8,
    availableUnits: 5,
    status: "available",
    floor: "Lantai 1",
    view: "Koridor",
    images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5"],
    amenities: ["WiFi", "Locker", "Shared Bathroom", "Reading Lamp"],
    breakfastIncluded: false,
    smokingAllowed: false,
    lastCleanedAt: "2026-04-08T06:45:00Z",
    accommodationId: "acc-3",
  },
  {
    id: "room-7",
    name: "Courtyard Double",
    roomCode: "CTY-02",
    type: "Standard Double",
    description: "Kamar double menghadap courtyard dengan akses cepat ke dapur bersama.",
    bedType: "1 Double Bed",
    capacity: 2,
    pricePerNight: 275000,
    sizeSqm: 16,
    totalUnits: 3,
    availableUnits: 1,
    status: "booked",
    floor: "Lantai 1",
    view: "Courtyard",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750"],
    amenities: ["WiFi", "Hot Shower", "Shared Pantry"],
    breakfastIncluded: true,
    smokingAllowed: true,
    lastCleanedAt: "2026-04-07T17:00:00Z",
    accommodationId: "acc-3",
  },
];

const paymentItems: PaymentItem[] = [
  {
    id: "pi-1",
    paymentId: "pay-1",
    type: "room",
    name: "Deluxe View Sawah",
    quantity: 3,
    unitPrice: 450000,
    totalPrice: 1350000,
    partnerId: "2",
    partnerName: "Homestay Bukit Hijau",
    refundable: true,
  },
  {
    id: "pi-2",
    paymentId: "pay-1",
    type: "addon_tour",
    name: "Paket Tur Sawah",
    quantity: 2,
    unitPrice: 90000,
    totalPrice: 180000,
    partnerId: "partner-tour-1",
    partnerName: "Desa Tours",
    refundable: true,
  },
  {
    id: "pi-3",
    paymentId: "pay-1",
    type: "addon_food",
    name: "Paket Kuliner Lokal",
    quantity: 2,
    unitPrice: 70000,
    totalPrice: 140000,
    partnerId: "partner-food-1",
    partnerName: "Warung Bu Ani",
    refundable: true,
  },
];

const paymentSplits: PaymentSplit[] = [
  {
    partnerId: "2",
    partnerName: "Homestay Bukit Hijau",
    amount: 1350000,
    platformFee: 67500,
    netAmount: 1282500,
    settlementStatus: "settled",
    settledAt: "2026-04-07",
  },
  {
    partnerId: "partner-tour-1",
    partnerName: "Desa Tours",
    amount: 180000,
    platformFee: 9000,
    netAmount: 171000,
    settlementStatus: "pending",
  },
  {
    partnerId: "partner-food-1",
    partnerName: "Warung Bu Ani",
    amount: 140000,
    platformFee: 7000,
    netAmount: 133000,
    settlementStatus: "pending",
  },
];

export const PAYMENTS: Payment[] = [
  {
    id: "pay-1",
    reservationId: "res-1",
    externalId: "MID-ORDER-20260407-001",
    method: "qris",
    status: "success",
    currency: "IDR",
    subtotal: 1670000,
    tax: 167000,
    platformFee: 83500,
    totalAmount: 1837000,
    items: paymentItems,
    splits: paymentSplits,
    paidAt: "2026-04-07",
    createdAt: "2026-04-07",
    updatedAt: "2026-04-07",
  },
];

export const SUBMISSION_EVENTS: Record<string, AccommodationSubmissionEvent[]> = {
  "acc-1": [
    {
      id: "evt-1",
      accommodationId: "acc-1",
      status: "submitted",
      title: "Pengajuan diterima",
      description: "Data penginapan masuk ke antrian verifikasi admin.",
      createdAt: "2026-03-01",
    },
    {
      id: "evt-2",
      accommodationId: "acc-1",
      status: "approved",
      title: "Pengajuan disetujui",
      description: "Penginapan aktif dan ditampilkan di platform.",
      createdAt: "2026-03-03",
    },
  ],
  "acc-2": [
    {
      id: "evt-3",
      accommodationId: "acc-2",
      status: "submitted",
      title: "Pengajuan diterima",
      description: "Admin sedang memeriksa foto, geo-tag, dan dokumen legal.",
      createdAt: "2026-04-06",
    },
  ],
  "acc-3": [
    {
      id: "evt-4",
      accommodationId: "acc-3",
      status: "submitted",
      title: "Pengajuan diterima",
      description: "Data masuk ke antrian review.",
      createdAt: "2026-04-02",
    },
    {
      id: "evt-5",
      accommodationId: "acc-3",
      status: "revision",
      title: "Perlu revisi",
      description: "Admin meminta perbaikan pada foto interior dan dokumen kesehatan.",
      createdAt: "2026-04-04",
      rejectionDetails: [
        "Foto interior kurang terang.",
        "Sertifikat kesehatan tidak valid.",
      ],
    },
  ],
};

export const ACCOMMODATION_RESERVATIONS: Reservation[] = [
  {
    id: "res-1",
    guestName: "Dina Pramesti",
    guestEmail: "dina@example.com",
    guestPhone: "081234567801",
    roomId: "room-1",
    roomName: "Deluxe View Sawah",
    accommodationId: "acc-1",
    checkIn: "2026-04-12",
    checkOut: "2026-04-15",
    totalPrice: 1350000,
    status: "confirmed",
    paymentStatus: "success",
    createdAt: "2026-04-07",
  },
  {
    id: "res-2",
    guestName: "Rudi Hartono",
    guestEmail: "rudi@example.com",
    guestPhone: "081234567802",
    roomId: "room-2",
    roomName: "Family Suite",
    accommodationId: "acc-1",
    checkIn: "2026-04-10",
    checkOut: "2026-04-12",
    totalPrice: 1700000,
    status: "checked_in",
    paymentStatus: "success",
    createdAt: "2026-04-04",
  },
  {
    id: "res-3",
    guestName: "Ayu Lestari",
    guestEmail: "ayu@example.com",
    guestPhone: "081234567803",
    roomId: "room-4",
    roomName: "Standard Room A",
    accommodationId: "acc-2",
    checkIn: "2026-04-18",
    checkOut: "2026-04-20",
    totalPrice: 640000,
    status: "pending",
    paymentStatus: "pending",
    createdAt: "2026-04-08",
  },
  {
    id: "res-4",
    guestName: "Kenji Sato",
    guestEmail: "kenji@example.com",
    guestPhone: "081234567804",
    roomId: "room-5",
    roomName: "Sky Loft",
    accommodationId: "acc-2",
    checkIn: "2026-04-09",
    checkOut: "2026-04-11",
    totalPrice: 1840000,
    status: "checked_out",
    paymentStatus: "success",
    createdAt: "2026-04-02",
  },
  {
    id: "res-5",
    guestName: "Bagus Raharjo",
    guestEmail: "bagus@example.com",
    guestPhone: "081234567805",
    roomId: "room-7",
    roomName: "Courtyard Double",
    accommodationId: "acc-3",
    checkIn: "2026-04-14",
    checkOut: "2026-04-16",
    totalPrice: 550000,
    status: "cancelled",
    paymentStatus: "refunded",
    createdAt: "2026-04-05",
  },
  {
    id: "res-6",
    guestName: "Nabila Putri",
    guestEmail: "nabila@example.com",
    guestPhone: "081234567806",
    roomId: "room-6",
    roomName: "Backpacker Pod",
    accommodationId: "acc-3",
    checkIn: "2026-04-19",
    checkOut: "2026-04-21",
    totalPrice: 360000,
    status: "confirmed",
    paymentStatus: "pending",
    createdAt: "2026-04-09",
  },
];

export const ACCOMMODATION_REVIEWS: Review[] = [
  {
    id: "rev-1",
    reviewerName: "Tanaka Hiroshi",
    targetId: "acc-1",
    targetType: "accommodation",
    rating: 5,
    comment:
      "Kamar bersih, staff sangat ramah, dan pemandangan pagi dari balkon luar biasa.",
    createdAt: "2026-04-06",
  },
  {
    id: "rev-2",
    reviewerName: "Maria Santos",
    targetId: "acc-1",
    targetType: "accommodation",
    rating: 4,
    comment: "Pengalaman menginap sangat nyaman, hanya WiFi malam hari sempat melambat.",
    createdAt: "2026-04-04",
  },
  {
    id: "rev-3",
    reviewerName: "Budi Santoso",
    targetId: "acc-2",
    targetType: "accommodation",
    rating: 5,
    comment: "Sky Loft-nya luas dan cocok untuk keluarga. Proses check-in cepat.",
    createdAt: "2026-04-03",
  },
  {
    id: "rev-4",
    reviewerName: "Yuki Yamamoto",
    targetId: "acc-3",
    targetType: "accommodation",
    rating: 3,
    comment:
      "Lokasi bagus untuk backpacker, tapi area kamar mandi bersama perlu lebih sering dibersihkan.",
    createdAt: "2026-03-30",
  },
  {
    id: "rev-5",
    reviewerName: "Rina Wulandari",
    targetId: "acc-2",
    targetType: "accommodation",
    rating: 4,
    comment: "Pemandangan malam indah, sarapan enak, staf helpfull untuk rekomendasi wisata.",
    createdAt: "2026-03-28",
  },
];

export const ACCOMMODATION_PROMOTIONS: Promotion[] = [
  {
    id: "promo-1",
    name: "Lebaran Escape",
    type: "seasonal_discount",
    discountValue: 15,
    discountType: "percentage",
    validFrom: "2026-04-01",
    validTo: "2026-04-30",
    applicableRoomIds: "all",
    applicableAccommodationIds: ["acc-1", "acc-2"],
    status: "active",
    usageCount: 18,
    revenueImpact: 12450000,
  },
  {
    id: "promo-2",
    name: "Stay4Save",
    type: "long_stay",
    discountValue: 250000,
    discountType: "fixed",
    validFrom: "2026-04-01",
    validTo: "2026-06-30",
    applicableRoomIds: ["room-1", "room-2"],
    applicableAccommodationIds: ["acc-1"],
    minStay: 4,
    status: "active",
    usageCount: 9,
    revenueImpact: 5600000,
  },
  {
    id: "promo-3",
    name: "EARLY10",
    type: "promo_code",
    discountValue: 10,
    discountType: "percentage",
    validFrom: "2026-04-10",
    validTo: "2026-05-31",
    applicableRoomIds: "all",
    applicableAccommodationIds: "all",
    promoCode: "EARLY10",
    status: "inactive",
    usageCount: 0,
    revenueImpact: 0,
  },
];

export const ACCOMMODATION_BANK_ACCOUNTS: BankAccount[] = [
  {
    id: "bank-1",
    accommodationId: "acc-1",
    accountHolderName: "PT Bukit Hijau Hospitality",
    bankName: "BCA",
    accountNumber: "1234567890",
    branch: "Wonosobo",
    swiftCode: "CENAIDJA",
    isVerified: true,
  },
  {
    id: "bank-2",
    accommodationId: "acc-2",
    accountHolderName: "Villa Puncak Embun",
    bankName: "Mandiri",
    accountNumber: "9988776655",
    branch: "Banjarnegara",
    swiftCode: "BMRIIDJA",
    isVerified: false,
  },
  {
    id: "bank-3",
    accommodationId: "acc-3",
    accountHolderName: "Guest House Cendana",
    bankName: "BNI",
    accountNumber: "4455667788",
    branch: "Wonosobo",
    swiftCode: "BNINIDJA",
    isVerified: true,
  },
];

export const ACCOMMODATION_WITHDRAWALS: WithdrawalRequest[] = [
  {
    id: "wd-1",
    accommodationId: "acc-1",
    amount: 2500000,
    status: "paid",
    requestedAt: "2026-04-01",
    paidAt: "2026-04-03",
  },
  {
    id: "wd-2",
    accommodationId: "acc-1",
    amount: 1800000,
    status: "pending",
    requestedAt: "2026-04-08",
  },
  {
    id: "wd-3",
    accommodationId: "acc-3",
    amount: 750000,
    status: "approved",
    requestedAt: "2026-04-06",
  },
];
