import type {
  BalanceTransaction,
  CommissionConfig,
  CoordinationRequest,
  DocumentVerificationState,
  Experience,
  Facility,
  FacilityInvoice,
  FacilityReservation,
  PartnerApplication,
  PartnerSubscription,
  ProfileSection,
  SubscriptionTier,
  TopPerformer,
  VillageBalance,
  VillageContact,
  VillageDashboardKpi,
  VillageProfile,
  VillageReview,
  VillageSocialMedia,
  VillageTag,
  VillageTagAssignment,
  VisitorStats,
} from "./types";

export const VILLAGE_CONTACTS: VillageContact[] = [
  { id: "vc-1", type: "phone", label: "Phone Utama", value: "+62 812-1111-2222", isPrimary: true, sortOrder: 0 },
  { id: "vc-2", type: "email", label: "Email Admin", value: "admin@sarialam.id", isPrimary: true, sortOrder: 1 },
  { id: "vc-3", type: "whatsapp", label: "WhatsApp CS", value: "+62 813-9999-8888", isPrimary: false, sortOrder: 2 },
  { id: "vc-4", type: "hotline", label: "Hotline Darurat", value: "+62 265-110", isPrimary: false, sortOrder: 3 },
];

export const VILLAGE_SOCIAL_MEDIA: VillageSocialMedia[] = [
  { id: "vsm-1", platform: "instagram", label: "Instagram Official", url: "https://instagram.com/sarialam.village", username: "@sarialam.village", sortOrder: 0 },
  { id: "vsm-2", platform: "facebook", label: "Facebook Page", url: "https://facebook.com/SariAlamVillage", username: "Sari Alam Village", sortOrder: 1 },
  { id: "vsm-3", platform: "youtube", url: "https://youtube.com/@sarialam", sortOrder: 2 },
  { id: "vsm-4", platform: "tiktok", url: "https://tiktok.com/@sarialam", username: "@sarialam", sortOrder: 3 },
  { id: "vsm-5", platform: "website", label: "Website Resmi", url: "https://sarialam.id", sortOrder: 4 },
];

export const VILLAGE_PROFILE_SECTIONS: ProfileSection[] = [
  {
    id: "vps-1",
    type: "history",
    title: "Sejarah Desa",
    content: { text: "Sari Alam has grown from an agricultural village into a tourism ecosystem focused on cultural preservation since 1985." },
    sortOrder: 0,
    isVisible: true,
  },
  {
    id: "vps-2",
    type: "vision_mission",
    title: "Visi & Misi",
    content: {
      vision: "Menjadi desa wisata unggulan berbasis budaya dan alam yang berkelanjutan.",
      mission: [
        "Melestarikan budaya lokal melalui pariwisata.",
        "Memberdayakan ekonomi masyarakat desa.",
        "Menjaga kelestarian lingkungan alam.",
      ],
    },
    sortOrder: 1,
    isVisible: true,
  },
  {
    id: "vps-3",
    type: "culture",
    title: "Budaya & Tradisi",
    content: { text: "Desa Sari Alam memiliki tradisi batik tulis, tari topeng, dan upacara panen raya yang digelar setiap tahun." },
    sortOrder: 2,
    isVisible: true,
  },
  {
    id: "vps-4",
    type: "geography",
    title: "Geografi",
    content: { text: "Terletak di kaki Gunung Manglayang, ketinggian 650 mdpl, suhu rata-rata 22°C. Luas wilayah 350 hektar." },
    sortOrder: 3,
    isVisible: true,
  },
];

export const AVAILABLE_TAGS: VillageTag[] = [
  { id: "tag-1", name: "Agro Tourism", category: "theme", icon: "leaf", isActive: true },
  { id: "tag-2", name: "Cultural Heritage", category: "theme", icon: "landmark", isActive: true },
  { id: "tag-3", name: "Eco Village", category: "certification", icon: "award", isActive: true },
  { id: "tag-4", name: "Craft Village", category: "attraction", icon: "palette", isActive: true },
  { id: "tag-5", name: "Nature Walk", category: "attraction", icon: "trees", isActive: true },
  { id: "tag-6", name: "Culinary Destination", category: "attraction", icon: "utensils", isActive: true },
  { id: "tag-7", name: "Community Based Tourism", category: "certification", icon: "users", isActive: true },
];

export const VILLAGE_TAG_ASSIGNMENTS: VillageTagAssignment[] = [
  { id: "vta-1", tagId: "tag-1", tag: AVAILABLE_TAGS[0], assignedAt: "2026-01-15" },
  { id: "vta-2", tagId: "tag-2", tag: AVAILABLE_TAGS[1], assignedAt: "2026-01-15" },
  { id: "vta-3", tagId: "tag-3", tag: AVAILABLE_TAGS[2], assignedAt: "2026-02-01" },
  { id: "vta-4", tagId: "tag-4", tag: AVAILABLE_TAGS[3], assignedAt: "2026-03-10" },
];

export const VILLAGE_PROFILE: VillageProfile = {
  villageName: "Sari Alam Tourism Village",
  address: "Jl. Raya Desa Sari Alam No. 12, Sukamaju, West Java",
  latitude: -6.9175,
  longitude: 107.6191,
  history: "Sari Alam has grown from an agricultural village into a tourism ecosystem focused on cultural preservation.",
  description: "A tourism village offering nature, culture, craft, and culinary experiences managed by local communities.",
  contacts: VILLAGE_CONTACTS,
  socialMediaLinks: VILLAGE_SOCIAL_MEDIA,
  profileSections: VILLAGE_PROFILE_SECTIONS,
  tags: VILLAGE_TAG_ASSIGNMENTS,
  contactPhone: "+62 812-1111-2222",
  contactEmail: "admin@sarialam.id",
  website: "https://sarialam.id",
  socialMedia: {
    instagram: "@sarialam.village",
    facebook: "Sari Alam Village",
    youtube: "https://youtube.com/@sarialam",
  },
  coverPhoto: "https://images.unsplash.com/photo-1625457228779-7cc7d8acbfff?w=1200&q=80",
  gallery: [
    "https://images.unsplash.com/photo-1568295967650-c234e48ab22a?w=800&q=80",
    "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80",
    "https://images.unsplash.com/photo-1589308078054-77c73d14abf6?w=800&q=80",
    "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
  ],
  videoUrl: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
  bankAccountName: "BUMDes Sari Alam",
  bankName: "Bank BNI",
  bankAccountNumber: "1234567890",
  taxId: "12.345.678.9-012.000",
  governmentServices: [
    {
      id: "gov-1",
      type: "clinic",
      name: "Puskesmas Sukamaju",
      address: "Jl. Kesehatan No. 7, Sukamaju",
      latitude: -6.91865,
      longitude: 107.6178,
      phone: "+62 265-123-456",
      operatingHours: "24 jam",
      notes: "Layanan IGD, ambulans, dan kesehatan umum.",
      priorities: ["open_24h", "emergency_ready"],
    },
    {
      id: "gov-2",
      type: "hospital",
      name: "RSUD Cibiru",
      address: "Jl. Raya Cibiru No. 90",
      latitude: -6.92222,
      longitude: 107.62511,
      phone: "+62 22-777-8899",
      operatingHours: "24 jam",
      notes: "Rujukan utama untuk kasus gawat darurat.",
      priorities: ["open_24h", "emergency_ready"],
    },
    {
      id: "gov-3",
      type: "police",
      name: "Polsek Sukamaju",
      address: "Jl. Bhayangkara No. 12",
      latitude: -6.91315,
      longitude: 107.62145,
      phone: "+62 265-110",
      operatingHours: "24 jam",
      notes: "Penanganan keamanan wisatawan dan patroli area.",
      priorities: ["open_24h", "emergency_ready"],
    },
  ],
};

export const VILLAGE_KPI: VillageDashboardKpi = {
  totalPartners: 48,
  pendingApprovals: 7,
  activeExperiences: 12,
  monthlyRevenue: 182500000,
  facilityUtilizationRate: 74,
  averageVillageRating: 4.6,
};

export const FACILITIES: Facility[] = [
  {
    id: "fac-1",
    name: "Village Hall Sari Alam",
    category: "monetizable",
    description: "Main hall for workshops, meetings, and performances.",
    address: "Jl. Utama No. 1",
    photos: ["hall-1.jpg"],
    isMonetizable: true,
    rentalPrice: 1500000,
    capacity: 250,
    utilizationRate: 82,
  },
  {
    id: "fac-2",
    name: "Community Health Clinic",
    category: "security",
    description: "Primary clinic for emergency and first aid support.",
    address: "Jl. Sehat No. 8",
    photos: ["clinic.jpg"],
    isMonetizable: false,
    utilizationRate: 58,
  },
  {
    id: "fac-3",
    name: "Village Market",
    category: "public",
    description: "Traditional market for local products and food.",
    address: "Jl. Pasar No. 3",
    photos: ["market.jpg"],
    isMonetizable: false,
    utilizationRate: 67,
  },
  {
    id: "fac-4",
    name: "Central Parking Area",
    category: "transportation",
    description: "Parking area for buses and private vehicles.",
    address: "Jl. Terminal No. 2",
    photos: ["parking.jpg"],
    isMonetizable: false,
    utilizationRate: 77,
  },
];

export const EXPERIENCES: Experience[] = [
  {
    id: "exp-1",
    name: "Traditional Batik Workshop",
    description: "Hands-on batik class with local artisans.",
    category: "craft",
    location: "Village Craft Center",
    latitude: -6.9180,
    longitude: 107.6195,
    startsAt: "2026-04-20T09:00:00",
    endsAt: "2026-04-20T12:00:00",
    capacity: 30,
    booked: 24,
    pricePerPerson: 175000,
    status: "published",
    contactPerson: "Ayu Rahma",
    cancellationPolicy: "Free cancellation up to 48 hours before the event.",
    facilitiesUsed: ["fac-1"],
  },
  {
    id: "exp-2",
    name: "Rice Field Sunrise Walk",
    description: "Guided early morning nature walk through terrace fields.",
    category: "nature",
    location: "North Terrace Route",
    latitude: -6.9200,
    longitude: 107.6210,
    startsAt: "2026-04-18T05:30:00",
    endsAt: "2026-04-18T07:30:00",
    capacity: 40,
    booked: 35,
    pricePerPerson: 85000,
    status: "ongoing",
    contactPerson: "Raka Nur",
    cancellationPolicy: "Reschedule allowed one time for weather reasons.",
    facilitiesUsed: [],
  },
  {
    id: "exp-3",
    name: "Village Culinary Night",
    description: "Culinary showcase featuring local family businesses.",
    category: "culinary",
    location: "Village Hall Sari Alam",
    latitude: -6.9175,
    longitude: 107.6191,
    startsAt: "2026-05-02T18:00:00",
    endsAt: "2026-05-02T21:00:00",
    capacity: 120,
    booked: 78,
    pricePerPerson: 125000,
    status: "draft",
    contactPerson: "Nina Putri",
    cancellationPolicy: "Full refund if canceled by organizer.",
    facilitiesUsed: ["fac-1"],
  },
];

export const PARTNER_APPLICATIONS: PartnerApplication[] = [
  {
    id: "app-1",
    villageId: "village-sari-alam",
    villageName: "Desa Sari Alam",
    villageApprovalStatus: "pending_review",
    organizationName: "Bukit Hijau Homestay",
    role: "accommodation",
    ownerName: "Hendra Kusuma",
    ownerEmail: "hendra@bukithijau.id",
    ownerPhone: "+62 812-1122-3344",
    businessType: "Homestay & Villa",
    description: "Homestay with 12 rooms, mountain-facing view, and local culinary packages.",
    address: "Jl. Puncak Hijau No. 4, Sari Alam",
    submittedAt: "2026-04-05",
    status: "under_review",
    partnerStatus: "pending",
    completionScore: 92,
    documents: [
      {
        type: "KTP",
        fileName: "ktp-hendra-kusuma.pdf",
        fileUrl: "https://example.com/docs/ktp-hendra-kusuma.pdf",
        uploadedAt: "2026-04-05T09:30:00",
      },
      {
        type: "NIB",
        fileName: "nib-bukit-hijau.pdf",
        fileUrl: "https://example.com/docs/nib-bukit-hijau.pdf",
        uploadedAt: "2026-04-05T10:00:00",
      },
      {
        type: "SIUP",
        fileName: "siup-bukit-hijau.pdf",
        fileUrl: "https://example.com/docs/siup-bukit-hijau.pdf",
        uploadedAt: "2026-04-05T10:15:00",
      },
    ],
    location: {
      latitude: -6.91642,
      longitude: 107.62188,
      address: "Jl. Puncak Hijau No. 4, Sari Alam",
      googleMapsUrl: "https://maps.google.com/?q=-6.91642,107.62188",
    },
    bankAccount: {
      bankName: "BCA",
      accountNumber: "1234567890",
      accountHolder: "Hendra Kusuma",
    },
    media: [
      {
        type: "photo",
        title: "Front Building",
        fileUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80",
        uploadedAt: "2026-04-05T11:00:00",
      },
      {
        type: "photo",
        title: "Room Interior",
        fileUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=80",
        uploadedAt: "2026-04-05T11:20:00",
      },
      {
        type: "video",
        title: "Property Walkthrough",
        fileUrl: "https://example.com/media/bukit-hijau-walkthrough.mp4",
        uploadedAt: "2026-04-05T11:45:00",
      },
    ],
    activityLog: [
      {
        id: "log-1-1",
        status: "pending",
        note: "Application submitted by partner.",
        createdAt: "2026-04-05T08:55:00",
      },
      {
        id: "log-1-2",
        status: "under_review",
        note: "Documents validated by village admin.",
        createdAt: "2026-04-06T10:15:00",
      },
    ],
    checklist: {
      businessInfo: true,
      documents: true,
      location: true,
      financial: true,
      media: false,
    },
    latestNote: "Please upload one additional room photo.",
  },
  {
    id: "app-2",
    villageId: "village-sari-alam",
    villageName: "Desa Sari Alam",
    villageApprovalStatus: "not_submitted",
    organizationName: "Sari Snack Corner",
    role: "sme",
    ownerName: "Melati Dewi",
    ownerEmail: "melati@sarisnack.id",
    ownerPhone: "+62 813-2233-4455",
    businessType: "Processed Food SME",
    description: "Village snack producer focused on cassava chips and banana crackers.",
    address: "Jl. Pasar Desa No. 9, Sari Alam",
    submittedAt: "2026-04-07",
    status: "pending",
    partnerStatus: "pending",
    completionScore: 76,
    documents: [
      {
        type: "KTP",
        fileName: "ktp-melati-dewi.pdf",
        fileUrl: "https://example.com/docs/ktp-melati-dewi.pdf",
        uploadedAt: "2026-04-07T09:10:00",
      },
    ],
    location: {
      latitude: -6.91892,
      longitude: 107.61877,
      address: "Jl. Pasar Desa No. 9, Sari Alam",
      googleMapsUrl: "https://maps.google.com/?q=-6.91892,107.61877",
    },
    bankAccount: {
      bankName: "BRI",
      accountNumber: "9876543210",
      accountHolder: "Melati Dewi",
    },
    media: [
      {
        type: "photo",
        title: "Production Area",
        fileUrl: "https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=1200&q=80",
        uploadedAt: "2026-04-07T10:00:00",
      },
    ],
    activityLog: [
      {
        id: "log-2-1",
        status: "pending",
        note: "Application submitted and waiting for initial review.",
        createdAt: "2026-04-07T08:40:00",
      },
    ],
    checklist: {
      businessInfo: true,
      documents: false,
      location: true,
      financial: true,
      media: false,
    },
  },
];

export const COORDINATION_REQUESTS: CoordinationRequest[] = [
  {
    id: "cor-1",
    organizerName: "Nusantara Experience Co.",
    eventName: "Village Culture Weekend",
    requestedFacilityId: "fac-1",
    requestedDate: "2026-05-10",
    participantsEstimate: 150,
    status: "terms_agreed",
    villageSharePercent: 25,
    organizerSharePercent: 60,
    platformSharePercent: 15,
  },
  {
    id: "cor-2",
    organizerName: "Green Trail Organizer",
    eventName: "Eco Tourism Camp",
    requestedDate: "2026-06-02",
    participantsEstimate: 60,
    status: "under_review",
    villageSharePercent: 25,
    organizerSharePercent: 60,
    platformSharePercent: 15,
  },
];

export const FACILITY_RESERVATIONS: FacilityReservation[] = [
  {
    id: "fres-1",
    facilityId: "fac-1",
    facilityName: "Village Hall Sari Alam",
    requesterName: "Nusantara Experience Co.",
    requesterRole: "organizer",
    startDate: "2026-05-10",
    endDate: "2026-05-10",
    participants: 150,
    purpose: "Village Culture Weekend opening event",
    status: "approved",
    notes: "Require stage and sound setup from 06:00.",
  },
  {
    id: "fres-2",
    facilityId: "fac-4",
    facilityName: "Central Parking Area",
    requesterName: "Sukamaju Community",
    requesterRole: "community",
    startDate: "2026-05-12",
    endDate: "2026-05-12",
    participants: 90,
    purpose: "Community bazaar parking support",
    status: "pending",
    notes: "Expected 4 buses and 30 private cars.",
  },
  {
    id: "fres-3",
    facilityId: "fac-2",
    facilityName: "Community Health Clinic",
    requesterName: "Health Office",
    requesterRole: "government",
    startDate: "2026-05-15",
    endDate: "2026-05-15",
    participants: 60,
    purpose: "Mobile vaccination support",
    status: "completed",
    notes: "Coordination complete with village volunteers.",
  },
];

export const VILLAGE_REVIEWS: VillageReview[] = [
  {
    id: "vr-1",
    entityType: "experience",
    targetName: "Traditional Batik Workshop",
    rating: 5,
    reviewerName: "Keiko Tanaka",
    comment: "Very educational and authentic. The instructors were amazing.",
    createdAt: "2026-04-04",
    hasResponse: true,
  },
  {
    id: "vr-2",
    entityType: "facility",
    targetName: "Village Hall Sari Alam",
    rating: 4,
    reviewerName: "Andi Pratama",
    comment: "Clean and spacious, but parking flow can be improved.",
    createdAt: "2026-04-06",
    hasResponse: false,
  },
  {
    id: "vr-3",
    entityType: "general",
    targetName: "Sari Alam Tourism Village",
    rating: 5,
    reviewerName: "Maria Gomez",
    comment: "Wonderful village atmosphere and very friendly community.",
    createdAt: "2026-04-08",
    hasResponse: false,
  },
];

export const TESTIMONIALS: import("./types").Testimonial[] = [
  {
    id: "tst-001",
    name: "Sari Dewi",
    role: "Pengunjung dari Jakarta",
    avatar: "https://i.pravatar.cc/80?img=47",
    content: "Pengalaman yang luar biasa! Desa ini menawarkan ketenangan yang sempurna jauh dari hiruk-pikuk kota. Warga lokal sangat ramah dan program wisatanya sangat berkesan.",
    rating: 5,
    isPinned: true,
    createdAt: "2026-03-15",
  },
  {
    id: "tst-002",
    name: "Budi Hartono",
    role: "Traveler — Surabaya",
    avatar: "https://i.pravatar.cc/80?img=12",
    content: "Kuliner tradisionalnya autentik dan pemandangannya menakjubkan. Sangat merekomendasikan paket 2 hari 1 malam di sini!",
    rating: 5,
    isPinned: true,
    createdAt: "2026-03-20",
  },
  {
    id: "tst-003",
    name: "Maya Putri",
    role: "Content Creator",
    avatar: "https://i.pravatar.cc/80?img=32",
    content: "Tempat yang perfect untuk konten! Estetika alami desa ini sangat fotogenik. Tim pengelola juga sangat kooperatif.",
    rating: 5,
    isPinned: true,
    createdAt: "2026-04-01",
  },
  {
    id: "tst-004",
    name: "Andi Kurniawan",
    role: "Wisatawan Keluarga",
    avatar: undefined,
    content: "Anak-anak sangat menikmati kegiatan pertanian tradisional. Ini adalah liburan keluarga terbaik kami tahun ini.",
    rating: 4,
    isPinned: false,
    createdAt: "2026-04-10",
  },
  {
    id: "tst-005",
    name: "Rina Susanti",
    role: "Peneliti Budaya — UGM",
    avatar: "https://i.pravatar.cc/80?img=55",
    content: "Sangat terkesan dengan pelestarian tradisi lokal. Masyarakatnya masih menjaga adat dengan baik sambil tetap terbuka untuk pariwisata.",
    rating: 4,
    isPinned: false,
    createdAt: "2026-04-18",
  },
];

// ─── Facility Invoices ───────────────────────────────────────

export const FACILITY_INVOICES: FacilityInvoice[] = [
  {
    id: "inv-001",
    invoiceNumber: "INV/SA/2026/001",
    coordinationRequestId: "cor-1",
    eventName: "Village Culture Weekend",
    organizerName: "Nusantara Experience Co.",
    eventDate: "2026-05-10",
    issuedAt: "2026-04-20",
    dueDate: "2026-04-27",
    status: "paid",
    paidAt: "2026-04-25",
    paymentMethod: "Bank Transfer",
    items: [
      {
        facilityId: "fac-1",
        facilityName: "Village Hall Sari Alam",
        rentalPrice: 1500000,
        durationDays: 1,
        subtotal: 1500000,
      },
    ],
    totalAmount: 1500000,
  },
  {
    id: "inv-002",
    invoiceNumber: "INV/SA/2026/002",
    coordinationRequestId: "cor-2",
    eventName: "Eco Tourism Camp",
    organizerName: "Green Trail Organizer",
    eventDate: "2026-06-02",
    issuedAt: "2026-04-28",
    dueDate: "2026-05-05",
    status: "pending_payment",
    items: [
      {
        facilityId: "fac-3",
        facilityName: "Village Market",
        rentalPrice: 800000,
        durationDays: 2,
        subtotal: 1600000,
      },
    ],
    totalAmount: 1600000,
  },
];

// ─── Village Balance ─────────────────────────────────────────

export const VILLAGE_BALANCE: VillageBalance = {
  currentBalance: 47_500_000,
  totalEarnedAllTime: 312_000_000,
  pendingIncoming: 1_600_000,
  totalWithdrawn: 264_500_000,
  lastUpdatedAt: "2026-04-29T08:00:00",
};

export const BALANCE_TRANSACTIONS: BalanceTransaction[] = [
  {
    id: "bt-001",
    type: "facility_rental",
    description: "Sewa Village Hall — Village Culture Weekend",
    amount: 1_500_000,
    balanceAfter: 47_500_000,
    referenceId: "inv-001",
    createdAt: "2026-04-25T10:30:00",
  },
  {
    id: "bt-002",
    type: "revenue_share",
    description: "Bagi hasil Event — Traditional Batik Workshop (25%)",
    amount: 3_750_000,
    balanceAfter: 46_000_000,
    referenceId: "exp-001",
    createdAt: "2026-04-22T14:00:00",
  },
  {
    id: "bt-003",
    type: "withdrawal",
    description: "Penarikan ke BNI — BUMDes Sari Alam",
    amount: -8_500_000,
    balanceAfter: 42_250_000,
    referenceId: "wd-2",
    createdAt: "2026-04-01T09:00:00",
  },
  {
    id: "bt-004",
    type: "revenue_share",
    description: "Bagi hasil Event — Eco Hiking Trail (25%)",
    amount: 2_200_000,
    balanceAfter: 50_750_000,
    referenceId: "exp-002",
    createdAt: "2026-03-28T11:45:00",
  },
  {
    id: "bt-005",
    type: "facility_rental",
    description: "Sewa Lapangan Olahraga — Community Tournament",
    amount: 600_000,
    balanceAfter: 48_550_000,
    referenceId: "inv-fac-5",
    createdAt: "2026-03-20T08:00:00",
  },
  {
    id: "bt-006",
    type: "withdrawal",
    description: "Penarikan ke BNI — BUMDes Sari Alam",
    amount: -15_000_000,
    balanceAfter: 47_950_000,
    referenceId: "wd-1",
    createdAt: "2026-03-15T10:00:00",
  },
];

// ─── Visitor Stats ───────────────────────────────────────────

export const VISITOR_STATS: VisitorStats = {
  totalThisMonth: 1_243,
  totalThisYear: 9_871,
  domesticPercent: 84,
  internationalPercent: 16,
  avgDurationDays: 1.8,
  repeatVisitorPercent: 28,
  monthlyTrend: [
    { month: "Nov", domestic: 620, international: 80 },
    { month: "Des", domestic: 750, international: 95 },
    { month: "Jan", domestic: 480, international: 60 },
    { month: "Feb", domestic: 530, international: 70 },
    { month: "Mar", domestic: 890, international: 120 },
    { month: "Apr", domestic: 1045, international: 198 },
  ],
  demographics: [
    { city: "Bandung", province: "Jawa Barat", count: 412, percentage: 33.1 },
    { city: "Jakarta", province: "DKI Jakarta", count: 318, percentage: 25.6 },
    { city: "Surabaya", province: "Jawa Timur", count: 147, percentage: 11.8 },
    { city: "Yogyakarta", province: "DIY", count: 98, percentage: 7.9 },
    { city: "Semarang", province: "Jawa Tengah", count: 76, percentage: 6.1 },
    { city: "Lainnya", province: "—", count: 192, percentage: 15.5 },
  ],
};

// ─── Top Performers ──────────────────────────────────────────

export const TOP_PERFORMERS: TopPerformer[] = [
  { id: "exp-001", name: "Traditional Batik Workshop", type: "experience", revenue: 15_000_000, bookings: 120, rating: 4.9, trend: "up", trendPercent: 22 },
  { id: "acc-001", name: "Homestay Sari Alam Indah", type: "accommodation", revenue: 12_400_000, bookings: 87, rating: 4.7, trend: "up", trendPercent: 8 },
  { id: "sme-001", name: "Keripik Melati", type: "sme", revenue: 8_200_000, bookings: 203, rating: 4.8, trend: "stable", trendPercent: 0 },
  { id: "exp-002", name: "Eco Hiking Trail", type: "experience", revenue: 8_800_000, bookings: 65, rating: 4.6, trend: "up", trendPercent: 15 },
  { id: "sme-002", name: "Batik Sari Craft", type: "sme", revenue: 5_600_000, bookings: 88, rating: 4.5, trend: "down", trendPercent: 5 },
];

// ─── Commission Config ───────────────────────────────────────

export const COMMISSION_CONFIG: CommissionConfig = {
  commissionPercent: 10,
  convenienceFeeFlat: 3500,
  splitOrganizer: 60,
  splitVillage: 25,
  splitPlatform: 15,
};

// ─── Subscription Tiers ──────────────────────────────────────

export const SUBSCRIPTION_TIERS: SubscriptionTier[] = [
  {
    name: "free",
    monthlyPrice: 0,
    commissionDiscount: 0,
    features: [
      { label: "Dashboard dasar", included: true },
      { label: "Manajemen produk & event", included: true },
      { label: "Approval partner", included: true },
      { label: "Komisi transaksi standar (10%)", included: true },
      { label: "Dashboard Analitik Lanjutan", included: false },
      { label: "Prioritas pencarian (SEO boost)", included: false },
      { label: "Kode promo mandiri", included: false },
      { label: "Laporan ekspor (PDF/Excel)", included: false },
    ],
  },
  {
    name: "pro",
    monthlyPrice: 299_000,
    commissionDiscount: 3,
    features: [
      { label: "Dashboard dasar", included: true },
      { label: "Manajemen produk & event", included: true },
      { label: "Approval partner", included: true },
      { label: "Komisi transaksi lebih rendah (7%)", included: true },
      { label: "Dashboard Analitik Lanjutan", included: true },
      { label: "Prioritas pencarian (SEO boost)", included: true },
      { label: "Kode promo mandiri", included: true },
      { label: "Laporan ekspor (PDF/Excel)", included: true },
    ],
  },
  {
    name: "government",
    monthlyPrice: 999_000,
    commissionDiscount: 5,
    features: [
      { label: "Semua fitur Pro", included: true },
      { label: "Komisi transaksi terendah (5%)", included: true },
      { label: "Manajemen aset digital BUMDes", included: true },
      { label: "Laporan untuk instansi pemerintah", included: true },
      { label: "Dedicated support", included: true },
      { label: "SLA 99.9% uptime", included: true },
      { label: "Multi-admin access", included: true },
      { label: "API akses data", included: true },
    ],
  },
];

export const PARTNER_SUBSCRIPTION: PartnerSubscription = {
  partnerId: "village-sari-alam",
  currentTier: "free",
  activatedAt: "2026-01-01",
};

// ─── Document Verification ───────────────────────────────────

export const DOCUMENT_VERIFICATION: DocumentVerificationState = {
  isTransactionEnabled: false,
  overallStatus: "pending_review",
  documents: [
    {
      id: "doc-001",
      type: "sk_kepala_desa",
      label: "SK Kepala Desa",
      fileUrl: "https://example.com/docs/sk-kepala-desa.pdf",
      uploadedAt: "2026-04-10",
      status: "pending_review",
      reviewNote: "Sedang diverifikasi tim DeWi",
    },
    {
      id: "doc-002",
      type: "akta_bumdes",
      label: "Akta BUMDes",
      status: "not_uploaded",
    },
    {
      id: "doc-003",
      type: "npwp",
      label: "NPWP BUMDes",
      fileUrl: "https://example.com/docs/npwp.pdf",
      uploadedAt: "2026-04-10",
      status: "verified",
    },
  ],
};
