import type {
  CoordinationRequest,
  Experience,
  Facility,
  PartnerApplication,
  VillageDashboardKpi,
  VillageProfile,
  VillageReview,
} from "./types";

export const VILLAGE_PROFILE: VillageProfile = {
  villageName: "Sari Alam Tourism Village",
  address: "Jl. Raya Desa Sari Alam No. 12, Sukamaju, West Java",
  latitude: -6.9175,
  longitude: 107.6191,
  history: "Sari Alam has grown from an agricultural village into a tourism ecosystem focused on cultural preservation.",
  description: "A tourism village offering nature, culture, craft, and culinary experiences managed by local communities.",
  contactPhone: "+62 812-1111-2222",
  contactEmail: "admin@sarialam.id",
  website: "https://sarialam.id",
  socialMedia: {
    instagram: "@sarialam.village",
    facebook: "Sari Alam Village",
    youtube: "https://youtube.com/@sarialam",
  },
  coverPhoto: "https://images.unsplash.com/photo-1625457228779-7cc7d8acbfff?w=1200&q=80",
  gallery: [
    "https://images.unsplash.com/photo-1568295967650-c234e48ab22a?w=800&q=80",
    "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80",
    "https://images.unsplash.com/photo-1589308078054-77c73d14abf6?w=800&q=80",
    "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
  ],
  videoUrl: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
  bankAccountName: "BUMDes Sari Alam",
  bankName: "Bank BNI",
  bankAccountNumber: "1234567890",
  taxId: "12.345.678.9-012.000",
  governmentServices: [
    {
      id: "gov-1",
      type: "clinic",
      name: "Puskesmas Sukamaju",
      address: "Jl. Kesehatan No. 7, Sukamaju",
      latitude: -6.91865,
      longitude: 107.6178,
      phone: "+62 265-123-456",
      operatingHours: "24 jam",
      notes: "Layanan IGD, ambulans, dan kesehatan umum.",
      priorities: ["open_24h", "emergency_ready"],
    },
    {
      id: "gov-2",
      type: "hospital",
      name: "RSUD Cibiru",
      address: "Jl. Raya Cibiru No. 90",
      latitude: -6.92222,
      longitude: 107.62511,
      phone: "+62 22-777-8899",
      operatingHours: "24 jam",
      notes: "Rujukan utama untuk kasus gawat darurat.",
      priorities: ["open_24h", "emergency_ready"],
    },
    {
      id: "gov-3",
      type: "police",
      name: "Polsek Sukamaju",
      address: "Jl. Bhayangkara No. 12",
      latitude: -6.91315,
      longitude: 107.62145,
      phone: "+62 265-110",
      operatingHours: "24 jam",
      notes: "Penanganan keamanan wisatawan dan patroli area.",
      priorities: ["open_24h", "emergency_ready"],
    },
  ],
};

export const VILLAGE_KPI: VillageDashboardKpi = {
  totalPartners: 48,
  pendingApprovals: 7,
  activeExperiences: 12,
  monthlyRevenue: 182500000,
  facilityUtilizationRate: 74,
  averageVillageRating: 4.6,
};

export const FACILITIES: Facility[] = [
  {
    id: "fac-1",
    name: "Village Hall Sari Alam",
    category: "monetizable",
    description: "Main hall for workshops, meetings, and performances.",
    address: "Jl. Utama No. 1",
    photos: ["hall-1.jpg"],
    isMonetizable: true,
    rentalPrice: 1500000,
    capacity: 250,
    utilizationRate: 82,
  },
  {
    id: "fac-2",
    name: "Community Health Clinic",
    category: "security",
    description: "Primary clinic for emergency and first aid support.",
    address: "Jl. Sehat No. 8",
    photos: ["clinic.jpg"],
    isMonetizable: false,
    utilizationRate: 58,
  },
  {
    id: "fac-3",
    name: "Village Market",
    category: "public",
    description: "Traditional market for local products and food.",
    address: "Jl. Pasar No. 3",
    photos: ["market.jpg"],
    isMonetizable: false,
    utilizationRate: 67,
  },
  {
    id: "fac-4",
    name: "Central Parking Area",
    category: "transportation",
    description: "Parking area for buses and private vehicles.",
    address: "Jl. Terminal No. 2",
    photos: ["parking.jpg"],
    isMonetizable: false,
    utilizationRate: 77,
  },
];

export const EXPERIENCES: Experience[] = [
  {
    id: "exp-1",
    name: "Traditional Batik Workshop",
    description: "Hands-on batik class with local artisans.",
    category: "craft",
    location: "Village Craft Center",
    startsAt: "2026-04-20T09:00:00",
    endsAt: "2026-04-20T12:00:00",
    capacity: 30,
    booked: 24,
    pricePerPerson: 175000,
    status: "published",
    contactPerson: "Ayu Rahma",
    cancellationPolicy: "Free cancellation up to 48 hours before the event.",
    facilitiesUsed: ["fac-1"],
  },
  {
    id: "exp-2",
    name: "Rice Field Sunrise Walk",
    description: "Guided early morning nature walk through terrace fields.",
    category: "nature",
    location: "North Terrace Route",
    startsAt: "2026-04-18T05:30:00",
    endsAt: "2026-04-18T07:30:00",
    capacity: 40,
    booked: 35,
    pricePerPerson: 85000,
    status: "ongoing",
    contactPerson: "Raka Nur",
    cancellationPolicy: "Reschedule allowed one time for weather reasons.",
    facilitiesUsed: [],
  },
  {
    id: "exp-3",
    name: "Village Culinary Night",
    description: "Culinary showcase featuring local family businesses.",
    category: "culinary",
    location: "Village Hall Sari Alam",
    startsAt: "2026-05-02T18:00:00",
    endsAt: "2026-05-02T21:00:00",
    capacity: 120,
    booked: 78,
    pricePerPerson: 125000,
    status: "draft",
    contactPerson: "Nina Putri",
    cancellationPolicy: "Full refund if canceled by organizer.",
    facilitiesUsed: ["fac-1"],
  },
];

export const PARTNER_APPLICATIONS: PartnerApplication[] = [
  {
    id: "app-1",
    organizationName: "Bukit Hijau Homestay",
    role: "accommodation",
    ownerName: "Hendra Kusuma",
    submittedAt: "2026-04-05",
    status: "under_review",
    completionScore: 92,
    checklist: {
      businessInfo: true,
      documents: true,
      location: true,
      financial: true,
      media: false,
    },
    latestNote: "Please upload one additional room photo.",
  },
  {
    id: "app-2",
    organizationName: "Sari Snack Corner",
    role: "sme",
    ownerName: "Melati Dewi",
    submittedAt: "2026-04-07",
    status: "pending",
    completionScore: 76,
    checklist: {
      businessInfo: true,
      documents: false,
      location: true,
      financial: true,
      media: false,
    },
  },
];

export const COORDINATION_REQUESTS: CoordinationRequest[] = [
  {
    id: "cor-1",
    organizerName: "Nusantara Experience Co.",
    eventName: "Village Culture Weekend",
    requestedFacilityId: "fac-1",
    requestedDate: "2026-05-10",
    participantsEstimate: 150,
    status: "terms_agreed",
    villageSharePercent: 25,
    organizerSharePercent: 60,
    platformSharePercent: 15,
  },
  {
    id: "cor-2",
    organizerName: "Green Trail Organizer",
    eventName: "Eco Tourism Camp",
    requestedDate: "2026-06-02",
    participantsEstimate: 60,
    status: "under_review",
    villageSharePercent: 25,
    organizerSharePercent: 60,
    platformSharePercent: 15,
  },
];

export const VILLAGE_REVIEWS: VillageReview[] = [
  {
    id: "vr-1",
    entityType: "experience",
    targetName: "Traditional Batik Workshop",
    rating: 5,
    reviewerName: "Keiko Tanaka",
    comment: "Very educational and authentic. The instructors were amazing.",
    createdAt: "2026-04-04",
    hasResponse: true,
  },
  {
    id: "vr-2",
    entityType: "facility",
    targetName: "Village Hall Sari Alam",
    rating: 4,
    reviewerName: "Andi Pratama",
    comment: "Clean and spacious, but parking flow can be improved.",
    createdAt: "2026-04-06",
    hasResponse: false,
  },
  {
    id: "vr-3",
    entityType: "general",
    targetName: "Sari Alam Tourism Village",
    rating: 5,
    reviewerName: "Maria Gomez",
    comment: "Wonderful village atmosphere and very friendly community.",
    createdAt: "2026-04-08",
    hasResponse: false,
  },
];
