import type {
  SmeOrder,
  SmeProduct,
  SmeProfile,
  SmePromotion,
  SmeReview,
  StockAdjustment,
} from "./types";

export const SME_PRODUCTS: SmeProduct[] = [
  {
    id: "sme-prod-1",
    name: "Keripik Singkong Pedas",
    description: "Keripik singkong renyah dengan bumbu cabai khas desa.",
    category: "Food",
    price: 18000,
    stock: 24,
    images: ["https://images.unsplash.com/photo-1599490659213-e2b9527bd087"],
    partnerId: "3",
    partnerName: "Sentra Produk Desa",
    approvalStatus: "approved",
    createdAt: "2026-03-01",
    updatedAt: "2026-04-10",
    subCategory: "Snack",
    minOrderQty: 1,
    maxOrderQty: 10,
    isAvailable: true,
    preparationTimeMinutes: 20,
    tags: ["spicy", "snack", "local"],
  },
  {
    id: "sme-prod-2",
    name: "Madu Hutan Asli",
    description: "Madu murni dari petani hutan sekitar desa wisata.",
    category: "Food",
    price: 95000,
    stock: 6,
    images: ["https://images.unsplash.com/photo-1587049352851-8d4e89133924"],
    partnerId: "3",
    partnerName: "Sentra Produk Desa",
    approvalStatus: "approved",
    createdAt: "2026-03-02",
    updatedAt: "2026-04-10",
    isAvailable: true,
    isFeatured: true,
    shelfLife: "12 months",
  },
  {
    id: "sme-prod-3",
    name: "Batik Tulis Motif Kawung",
    description: "Batik tulis handmade dengan pewarna alami.",
    category: "Craft",
    price: 275000,
    stock: 3,
    images: ["https://images.unsplash.com/photo-1604357209793-fca5dca89f97"],
    partnerId: "3",
    partnerName: "Sentra Produk Desa",
    approvalStatus: "pending",
    createdAt: "2026-03-05",
    updatedAt: "2026-04-08",
    isAvailable: true,
    weightGram: 350,
  },
];

export const SME_ORDERS: SmeOrder[] = [
  {
    id: "sme-order-1",
    customerId: "cust-1",
    customerName: "Dewi Lestari",
    customerPhone: "0812000111",
    customerEmail: "dewi@example.com",
    items: [
      {
        productId: "sme-prod-1",
        productName: "Keripik Singkong Pedas",
        quantity: 2,
        unitPrice: 18000,
        subtotal: 36000,
      },
    ],
    totalPrice: 36000,
    status: "ready_for_pickup",
    paymentStatus: "success",
    estimatedPickupTime: "2026-04-11T15:00:00+07:00",
    specialInstructions: "Please pack in paper bag",
    smeId: "3",
    smeName: "Sentra Produk Desa",
    createdAt: "2026-04-11T10:15:00+07:00",
    updatedAt: "2026-04-11T12:30:00+07:00",
  },
  {
    id: "sme-order-2",
    customerId: "cust-2",
    customerName: "Andi Nugroho",
    customerPhone: "0812000222",
    customerEmail: "andi@example.com",
    items: [
      {
        productId: "sme-prod-2",
        productName: "Madu Hutan Asli",
        quantity: 1,
        unitPrice: 95000,
        subtotal: 95000,
      },
    ],
    totalPrice: 95000,
    status: "preparing",
    paymentStatus: "success",
    estimatedPickupTime: "2026-04-11T17:00:00+07:00",
    smeId: "3",
    smeName: "Sentra Produk Desa",
    createdAt: "2026-04-11T11:00:00+07:00",
    updatedAt: "2026-04-11T11:30:00+07:00",
  },
  {
    id: "sme-order-3",
    customerId: "cust-3",
    customerName: "Sari W",
    customerPhone: "0812000333",
    customerEmail: "sari@example.com",
    items: [
      {
        productId: "sme-prod-3",
        productName: "Batik Tulis Motif Kawung",
        quantity: 1,
        unitPrice: 275000,
        subtotal: 275000,
      },
    ],
    totalPrice: 275000,
    status: "pending_payment",
    paymentStatus: "pending",
    smeId: "3",
    smeName: "Sentra Produk Desa",
    createdAt: "2026-04-11T08:45:00+07:00",
    updatedAt: "2026-04-11T08:45:00+07:00",
  },
];

export const SME_PROMOTIONS: SmePromotion[] = [
  {
    id: "sme-promo-1",
    name: "Weekend Snack Sale",
    type: "product_discount",
    discountType: "percentage",
    discountValue: 10,
    validFrom: "2026-04-01",
    validTo: "2026-04-30",
    applicableProductIds: ["sme-prod-1"],
    status: "active",
  },
  {
    id: "sme-promo-2",
    name: "First Purchase Voucher",
    type: "first_purchase",
    discountType: "fixed",
    discountValue: 15000,
    validFrom: "2026-04-01",
    validTo: "2026-05-31",
    applicableProductIds: "all",
    promoCode: "FIRSTDEWI",
    status: "active",
  },
];

export const SME_REVIEWS: SmeReview[] = [
  {
    id: "sme-review-1",
    reviewerName: "Rizal",
    targetId: "sme-prod-1",
    targetType: "product",
    rating: 5,
    comment: "Fresh and crispy, pickup process was smooth.",
    createdAt: "2026-04-10",
    response: "Thank you, we are happy you enjoyed it.",
  },
  {
    id: "sme-review-2",
    reviewerName: "Nina",
    targetId: "sme-prod-2",
    targetType: "product",
    rating: 3,
    comment: "Taste is good, but pickup time was slightly delayed.",
    createdAt: "2026-04-09",
  },
];

export const SME_PROFILE: SmeProfile = {
  id: "sme-profile-1",
  villageId: "village-sari-alam",
  villageName: "Desa Sari Alam",
  villageApprovalStatus: "approved",
  businessName: "Sentra Produk Desa",
  businessType: "food",
  description: "SME collective focusing on food and craft products from local artisans.",
  locationAddress: "Jl. Pasar Wisata No. 7, Wonosobo",
  latitude: -7.361,
  longitude: 109.908,
  contactPhone: "0812111000",
  contactEmail: "sme@mitradewi.id",
  operatingHours: {
    monday: "08:00-17:00",
    tuesday: "08:00-17:00",
    wednesday: "08:00-17:00",
    thursday: "08:00-17:00",
    friday: "08:00-17:00",
    saturday: "08:00-18:00",
    sunday: "09:00-16:00",
  },
  photos: [
    "https://images.unsplash.com/photo-1556740749-887f6717d7e4",
    "https://images.unsplash.com/photo-1534723452862-4c874018d66d",
  ],
  bankAccountName: "Sentra Produk Desa",
  bankName: "Bank BCA",
  bankAccountNumber: "1234567890",
};

export const SME_STOCK_ADJUSTMENTS: StockAdjustment[] = [
  {
    id: "stock-adj-1",
    productId: "sme-prod-1",
    productName: "Keripik Singkong Pedas",
    type: "out",
    quantity: 4,
    reason: "Order picked up",
    createdAt: "2026-04-11T13:20:00+07:00",
  },
  {
    id: "stock-adj-2",
    productId: "sme-prod-2",
    productName: "Madu Hutan Asli",
    type: "in",
    quantity: 10,
    reason: "Weekly restock",
    createdAt: "2026-04-10T09:00:00+07:00",
  },
];
